main: com.alpsbte.navigator.NavigatorPlugin
version: 3.2
api-version: 1.12.2
name: AlpsBTE-Navigator
author: R3tuxn
depend: [Multiverse-Core, Plot-System, LeakParkour]

commands:
  navigator:
    description: open the navigator menu
    usage: /navigator
    permission: alpsbte.navigator
  event:
    description: connect to the event server
    usage: /event
    permission: alpsbte.joinEvent
  tpp:
    description: teleport to another player
    usage: /tpp <player>
    permission: alpsbte.tpp
  hub:
    description: teleport to the hub world
    usage: /hub
    permission: alpsbte.hub
  nreload:
    description: reload AlpsBTE-Navigator config file
    usage: /nreload
    permission: alpsbte.nreload
  sethologram:
    description: Sets the position of a hologram
    usage: /sethologram <name>
    permission: alpsbte.admin

permissions:
  alpsbte.joinEventStaff:
    description: permission to join event server as staff member
    default: op