main: github.AlpsBTE_Navigator.AlpsBTE_Navigator
version: 3.0
api-version: 1.12.2
name: AlpsBTE-Navigator
author: R3tuxn
depend: [Multiverse-Core, Plot-System]

commands:
  navigator:
    description: open the navigator menu
    usage: /navigator
    permission: alpsbte.navigator
  event:
    description: connect to the event server
    usage: /event
    permission: alpsbte.joinEvent
  nreload:
    description: reload AlpsBTE-Navigator config file
    usage: /nreload
    permission: alpsbte.nreload

permissions:
  alpsbte.joinEventStaff:
    description: permission to join event server as staff member
    default: op